

// ADMIN CONSTANTS
export const ADMIN_REGISTER_FAIL = "ADMIN_REGISTER_FAIL";
export const ADMIN_REGISTER_SUCCESS = "ADMIN_REGISTER_SUCCESS";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const VENDOR_PROFILE_FAIL = "VENDOR_PROFILE_FAIL";
export const VENDOR_PROFILE_SUCCESS = "VENDOR_PROFILE_SUCCESS";


// USER 
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_FAIL = "USER_PROFILE_UPDATE_FAIL";

// VENDOR 
export const VENDOR_REGISTER_FAIL = "VENDOR_REGISTER_FAIL";
export const VENDOR_REGISTER_SUCCESS = "VENDOR_REGISTER_SUCCESS";
export const VENDOR_LOGIN_FAIL = "VENDOR_LOGIN_FAIL";
export const VENDOR_LOGIN_SUCCESS = "VENDOR_LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const VENDOR_PROFILE_UPDATE_SUCCESS = "VENDOR_PROFILE_UPDATE_SUCCESS";
export const VENDOR_PROFILE_UPDATE_FAIL = "VENDOR_PROFILE_UPDATE_FAIL";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";


// Password change
export const PASSWORD_CHANGE_SUCCESS = "PASSWORD_CHANGE_SUCCESS";
export const PASSWORD_CHANGE_FAIL = "PASSWORD_CHANGE_FAIL";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL";
export const RESET_VENDOR_PASSWORD_SUCCESS = "RESET_VENDOR_PASSWORD_SUCCESS";
export const RESET_VENDOR_PASSWORD_FAIL = "RESET_VENDOR_PASSWORD_FAIL";
export const RESET_USER_PASSWORD_SUCCESS = "RESET_USER_PASSWORD_SUCCESS";
export const RESET_USER_PASSWORD_FAIL = "RESET_USER_PASSWORD_FAIL";

//OTP
export const SEND_USER_OTP_SUCCESS = "SEND_USER_OTP_SUCCESS";
export const SEND_USER_OTP_FAIL = "SEND_USER_OTP_FAIL";
export const VERIFY_USER_OTP_SUCCESS = "VERIFY_USER_OTP_SUCCESS";
export const VERIFY_USER_OTP_FAIL = "VERIFY_USER_OTP_FAIL";
export const RESEND_USER_OTP_SUCCESS = "RESEND_USER_OTP_SUCCESS";
export const RESEND_USER_OTP_FAIL = "RESEND_USER_OTP_FAIL";
export const SET_CURRENT_STEP = "SET_CURRENT_STEP"
    
export const SEND_VENDOR_OTP_SUCCESS = "SEND_VENDOR_OTP_SUCCESS";
export const SEND_VENDOR_OTP_FAIL = "SEND_VENDOR_OTP_FAIL";
export const VERIFY_VENDOR_OTP_SUCCESS = "VERIFY_VENDOR_OTP_SUCCESS";
export const VERIFY_VENDOR_OTP_FAIL = "VERIFY_VENDOR_OTP_FAIL";
export const RESEND_VENDOR_OTP_SUCCESS = "RESEND_VENDOR_OTP_SUCCESS";
export const RESEND_VENDOR_OTP_FAIL = "RESEND_VENDOR_OTP_FAIL"